version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    volumes:
    - ./redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - ./postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=RM4L6X6An4wpLKQE
    - DB_NAME=gitlabhq
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:10.6.4
    volumes:
    - ./gitlab:/home/git/data:Z
    - ./certs:/certs
    ports:
    - "222:22"
    - "9000:80"
    depends_on:
    - registry
    - redis
    - postgresql
    environment:
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=RM4L6X6An4wpLKQE
    - DB_NAME=gitlabhq
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - GITLAB_HOST={{YOUR_IP}}
    - GITLAB_PORT=9000
    - GITLAB_SSH_PORT=222
    - TZ=Europe/Madrid
    - GITLAB_TIMEZONE=Madrid
    - GITLAB_SECRETS_DB_KEY_BASE=UPkayRc9dPgQ7wCgyvKB7CQXF4XH8AB8kTDfjUjLaqqW6Qt4JsdYraLYct295Rb9
    - GITLAB_SECRETS_SECRET_KEY_BASE=cf8FPn8hj6ReuDhL8bbcdsyL5RFBzUS2QRDSGu37CVSYX3yQ7xy5DZaq3JnPmtzh
    - GITLAB_SECRETS_OTP_KEY_BASE=FYSygHSeBeJF4z9J6jCtj5yFw5QKKXsz2rkKGnhMwGyAf6BxLKFRuFpByUp6grqY
    - GITLAB_ROOT_PASSWORD=8eGBCXhN
    - GITLAB_ROOT_EMAIL=git@gitlab
    - GITLAB_REGISTRY_ENABLED=true
    - GITLAB_REGISTRY_HOST={{YOUR_IP}}
    - GITLAB_REGISTRY_PORT=9001
    - GITLAB_REGISTRY_API_URL=http://registry:5000
    - GITLAB_REGISTRY_KEY_PATH=/certs/registry.key

  ci_runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
    - ./runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock

  registry:
    image: registry
    restart: always
    ports:
    - "9001:5000"
    expose:
    - "5000"
    volumes:
    - ./gitlab/shared/registry:/registry
    - ./certs:/certs
    environment:
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
    - REGISTRY_AUTH_TOKEN_REALM=http://gitlab/jwt/auth
    - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
    - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.crt
    - REGISTRY_STORAGE_DELETE_ENABLED=true
